release-date = "2022-03-24"

[[entries]]
id = "4b4add90-f1a2-48bb-af2f-a74d8f45f663"
type = "hygiene"
description = "update project structure to use Poetry as the build system and Slap for tooling"
author = "@NiklasRosenstein"
