[[entries]]
id = "b6dd5dd2-3cd9-466d-85fe-f0a4b2da82bc"
type = "improvement"
description = "add support for baserow 1.16.0 workspaces, trailing slashes on urls"
author = "@luc-languagetools"
pr = "https://github.com/NiklasRosenstein/python-baserow-client/pull/7"

[[entries]]
id = "89797d82-9b18-4bd7-82ba-17b1ecb85123"
type = "improvement"
description = "Upgrade from `databind 1.x` to `4.x`"
author = "@NiklasRosenstein"
